name: navigation
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../core
  core_ui:
    path: ../core_ui
  domain:
    path: ../domain

  auth:
    path: ../features/auth
  onboarding:
    path: ../features/onboarding
  paywall:
    path: ../features/paywall
  home:
    path: ../features/home
  doc_preview:
    path: ../features/doc_preview

  auto_route: ^10.0.1

dev_dependencies:
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15
  injectable_generator: ^2.7.0
