targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        options:
          auto_register: true
          class_name_pattern:
            "Repository$|Provider$|UseCase$"
          file_name_pattern: "_repository$|_provider$|_usecase$"