name: core
publish_to: none
description: Project core module

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.29.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  domain:
    path: ../domain
  data:
    path: ../data
  navigation:
    path: ../navigation

  get_it: ^8.0.3
  flutter_bloc: ^9.1.1
  easy_localization: ^3.0.7+1
  url_launcher: ^6.3.1
  intl: ^0.19.0
  permission_handler: ^11.2.1
  injectable: ^2.5.0
  dev: ^1.0.0
  fcuuid_kit: ^1.0.0
  in_app_review: ^2.0.10
  share_plus: ^11.0.0
  flutter_dotenv: ^5.2.1
  printing: 5.14.2
  cunning_document_scanner: ^1.2.3
  pdf_render: ^1.4.12
  uuid: ^4.5.1
  path_provider: ^2.1.2
  path: ^1.9.0
  purchases_flutter: ^8.10.0
  syncfusion_flutter_pdf: ^29.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.7.0
  build_runner: ^2.4.15

flutter:
  assets:
    - resources/lang/